language: java

dist: trusty

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

# define all stages
stages:
  - build
  - test

# define what build stage will do
build:
  stage: build
  sccript:
    - ./gradlew clean assemble

# define what test stage will do
unit_test:
  stage: test
  sccript:
    - ./gradlew test