language: java

dist: trusty

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

# define all stages
stages:
  - name: pull_request
    if: type IN (pull_request)
  - name: master
    if: branch = master AND type = push AND fork = false
  - name: release
    if: branch = release AND type = push AND fork = false

jobs:
  include:
    #define what to do in case of pull request
    - stage: pull_request
      script:
        - echo NOGOMI - this is pull request build
        - ./gradlew clean assemble
        - ./gradlew test
        -
    #define what to do in case of merge to master
    - stage: master
      script:
        - echo NOGOMI - this is master build
        - ./gradlew clean assemble
        - ./gradlew test

    #define what to do in case of release
    - stage: release
      script:
        - echo NOGOMI - this is release build
        - ./gradlew clean install
        - ./gradlew test
        - ./gradlew bintrayUpload