language: java

dist: trusty

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

# define all stages
stages:
  - build
  - test

jobs:
  include:
    #define what build stage will do
    - stage: build
      sccript:
        - ./gradlew clean assemble
    #define what test stage will do
    - stage: test
      script:
        - ./gradlew test